# config/packages/csrf.yaml
framework:
    form:
        csrf_protection:
            enabled: true
            field_name: _token
    csrf_protection:
        enabled: true

when@test:
    framework:
        csrf_protection:
            enabled: false